title: "Maximizeaza-ti Potentialul"
email: your-email@example.com
description: >-
  "Maximizeaza-ti Potentialul" este un blog comprehensiv de coaching de
  performanta conceput pentru a ajuta persoanele sa isi atinga potentialul lor
  maxim in toate aspectele vietii. Echipa noastra de antrenori expert ofera
  sfaturi practice, sfaturi si inspiratie pentru a ajuta persoanele sa isi
  sporeasca productivitatea, sa construiasca obiceiuri sanatoase si sa
  depaseasca obstacolele pe drumul catre succes. Alatura-te noua in aceasta
  calatorie pentru a-ti elibera potentialul tau complet si a-ti atinge
  obiectivele.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
# logo: "/assets/images/88x88.png"
# masthead_title: "My Custom Title"
locale: ro

plugins:
  - jekyll-include-cache
  - jekyll-feed

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true

  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

include:
  - _pages
