title: "Maximize Your Potential: A Performance Coaching Blog"
email: your-email@example.com
description: >-
  “Maximize Your Potential” is a comprehensive performance coaching blog
  designed to help individuals achieve their full potential in all areas of
  life. Our team of expert coaches provides practical advice, tips, and
  inspiration to help individuals boost their productivity, build healthy
  habits, and overcome obstacles on the path to success. Join us on this
  journey to unleash your full potential and achieve your goals.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
# logo: "/assets/images/88x88.png"
# masthead_title: "My Custom Title"

plugins:
  - jekyll-include-cache
  - jekyll-feed

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true

  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

include:
  - _pages
